version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    container_name: micro-authentication-api
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: micro-authentication-db
    ports:
      - "27018:27017"
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: admin
      DATABASE_URL: micro-authentication-mongodb

  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: "micro-authentication-rabbitmq"
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  rabbitmq_data:
    driver: local
